### ISSUE TITLE
current working directory question

### ISSUE THREAD

**Issue by saidbelkacem** [Civitasv/cmake-tools.nvim#17]
First: thanks for the plugin, love it :+1: 

Here my little issue:
I start neovim from my home directory, I open a c file from my dev folder (I use fzf-lua). I have an autocommand that change into this directory and !pwd is returning the right path.
But when I run Cmake generate, the build directory is created in home.
This behaviour does not occur with shaturs neovim-tasks. Here the build dir is always right.

**Comment by LinHeLurking** [comment]
I've found the same bug. It seems that the plugin set cmake direcory at start, which is the directory you launch nvim. If you are using some other plugins to switch project or switch directory, the cmake build directory is in a wrong place.

Maybe the plugin should look up cmake directory by `vim.fn.getcwd()` everytime instead of starting up time.

**Comment by Civitasv** [comment]
We use `vim.loop.cwd()` to get current workding directory. Can you use `:lua print(vim.loop.cwd())` to check if it changes when you open another c file?

**Comment by saidbelkacem** [comment]
I already did that. vim.loop.cwd gives me the correct working directory.

**Comment by Civitasv** [comment]
Thanks, @saidbelkacem, I've found why it behaves like this, will fix it today.

**Comment by Civitasv** [comment]
See 913d491.

**Comment by saidbelkacem** [comment]
Sorry for being late :-)
Just want to thank you very much :-)
