### ISSUE TITLE
Cannot configure preset due to an error

### ISSUE THREAD

**Issue by PabloPicose** [Civitasv/cmake-tools.nvim#268]
**Bug description**
Unable to execute CMakeSelectConfigurePreset in any project with a preset configuration at least, attempting to do it again cleaning the cache doesn't work
`
Error executing vim.schedule lua callback: ...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:764: attempt to call upvalue 'callback' (a table value)
stack traceback:
	...hare/nvim/lazy/cmake-tools.nvim/lua/cmake-tools/init.lua:764: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
`

**Steps to reproduce**
Open nvim, call CMakeSelectConfigurePreset, a error message appears

**Environment**

- OS: LinuxMint 21.3

**Comment by davidscholberg** [comment]
I encountered this error as well with `CMakeSelectBuildType` on version d8eb4372fff47028c36f6bec6a8318b166092ed0 (the latest version as of this writing). I reverted to version e16994847af7e630e2568621aae0f28537a6952c (the previous commit) and things are working again.

**Comment by vimkim** [comment]
For those who are struggling with this issue, I **found a simple, temporary workaround.**

You can avoid this issue by manually creating compile_commands.json by yourself.

```bash
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --preset <mypreset>
ln -s <build_dir>/compile_commands.json ./compile_commands.json
```

Since I failed running `:CMakeSelectConfigurePresets` inside neovim, I did it by myself and it works.

I'll add -DCMAKE_EXPORT_COMPILE_COMMANDS=ON by myself until this issue gets fixed.
Hopefully this gets fixed soon. Thanks for the amazing plugin.
